// import  './01-基础数据类型'
// import './02-数组和元祖类型'
// import './03-枚举类型'
// import './04-any-void类型'
// import './05-Never和Object类型'
// import './06-类型断言'
// import './07-变量声明和结构'
// import './08-接口类型'
// import './09-可选属性和索引签名'
import './10索引签名和只读属性'
